default_context:
  package_name: "sunxspex"
  module_name: "sunxspex"
  short_description: "A package for solar X-ray spectroscopy."
  long_description: "file: README.rst"
  author_name: "The SunPy Community"
  author_email: "sunpy@googlegroups.com"
  license: "BSD 3-Clause"
  project_url: "https://sunxspex.readthedocs.io"
  github_repo: "sunpy/sunxspex"
  minimum_python_version: "3.7"
  use_compiled_extensions: "n"
  include_example_code: "n"
