target-version = "py39"
line-length = 120
exclude = [
  ".git,",
  "__pycache__",
  "build",
  "sunkit_spex/version.py",
  "sunkit_spex/legacy/fitting"
]

[lint]
select = ["E", "F", "W", "UP", "PT"]
extend-ignore = [
  # pycodestyle (E, W)
  "E501", # LineTooLong                             # TODO! fix
  # pytest (PT)
  "PT001", # Always use pytest.fixture()
  "PT004", # Fixtures which don't return anything should have leading _
  "PT007", # Parametrize should be lists of tuples  # TODO! fix
  "PT011", # Too broad exception assert             # TODO! fix
  "PT023", # Always use () on pytest decorators
]


[lint.per-file-ignores]
# Part of configuration, not a package.
"setup.py" = ["INP001"]
"conftest.py" = ["INP001"]
"docs/conf.py" = ["E402", "F403"]
"docs/*.py" = [
  "INP001",  # Implicit-namespace-package. The examples are not a package.
]
"__init__.py" = ["E402", "F401", "F403"]
"test_*.py" = ["B011", "D", "E402", "PGH001", "S101"]
# Need to import clients to register them, but don't use them in file
#"sunpy/net/__init__.py" = ["F811"]

[lint.pydocstyle]
convention = "numpy"

[lint.flake8-pytest-style]
parametrize-names-type = "csv"
